# Question 1

Consider an undirected graph $G(V, E)$ with vertices $V = {1, . . . , n}$ and edges $E$. Let $N(i)$
denote the set of vertices that are connected to vertex $i ∈ V$ with an edge. The distance
$d_{ij} > 0$ of the edge $(i, j) ∈ E$ between $i$ and $j ∈ N(i)$ is given. Consider the system of
equations
$$f_i = \min_{j∈N(i)}
\{d_{ij} + f_j\}, i ∈ \{1, . . . , n − 1\} \text{ and } f_n = 0.$$
Show that (i) $f_i$
is the length of the shortest path from vertex $i$ to $n$, (ii) the equations have
a unique solution for $f_i, i ∈ \{1, . . . , n − 1\}$.

## i)

We will prove by strong induction.\
Let $t_i$ be the optimal distance from node $i$ to $n$. We will show that for all optimal distances $D$, if $t_i=D$, then $f_i=D$, and $t_i=f_i$.\
Base case: $D=0$. For node $n$, $t_i=0$, and so does $f_i=0$ by definition.\
Inductive assumption: For all $d<D$ for some $D$, assume $f_i=t_i=d$. Then we wish to show that if $t_j=D$, then $f_j=D=t_j$.\
Proof: Let $i$ be any node with $t_i=D$. Then the shortest path travels to some neighbor $k$ that where $t_k = t_i - d_{ik} = D - d_{ik} < D$, which from our inductive assumption, $t_k=f_k$. Now consider the value of 
$$f_i = \min_{j∈N(i)} \{d_{ij} + f_j\} \leq d_{ik} + f_k = d_{ik} + t_i - d_{ik} = D$$
and
$$f_i = \min_{j∈N(i)} \{d_{ij} + f_j\} \geq D$$
by definition, so $f_i = D = t_i$.

## ii) Change
We will prove by contradiction.\
Assume that there is not a unique solution for the optimal path length, i.e., there are multiple optimal path lengths. Then it must be the case that for two solutions $x, y, x < y$ or $y < x$ since the values associated with each path are unique real numbers. But then that would imply that one value is optimal (lower) compared to the other. So it cannot be that there are multiple optimal path lengths. Thus the equations must only have one unique solution.

# Question 2

In [55]:
import numpy as np

def min_matrix_multiplications(m):
    n = len(m) - 1

    C = np.zeros((n, n), dtype=np.int64)

    for length in range(2, n + 1):

        for i in range(n - length + 1):
            j = i + length - 1
            C[i][j] = min(C[i][k] + C[k+1][j] + m[i] * m[k+1] * m[j+1] for k in range(i, j))


    print(C)
    return C

m1 = [10, 5, 20, 10, 2, 100]
print(f"Minimum number of multiplications for {m1} is {min_matrix_multiplications(m1)[0][-1]}\n")

m2 = [4, 50, 12, 60, 1, 100, 3]
print(f"Minimum number of multiplications for {m2} is {min_matrix_multiplications(m2)[0][-1]}")

[[   0 1000 1500  700 2700]
 [   0    0 1000  600 1600]
 [   0    0    0  400 4400]
 [   0    0    0    0 2000]
 [   0    0    0    0    0]]
Minimum number of multiplications for [10, 5, 20, 10, 2, 100] is 2700

[[    0  2400  5280  1520  1920  1832]
 [    0     0 36000  1320  6320  1770]
 [    0     0     0   720  1920  1056]
 [    0     0     0     0  6000   480]
 [    0     0     0     0     0   300]
 [    0     0     0     0     0     0]]
Minimum number of multiplications for [4, 50, 12, 60, 1, 100, 3] is 1832
